// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD8kmHLio4pO2VMozRtKGYzq76Rbrcg7Zs',
    appId: '1:932823267060:web:08d557990566c7659c10a1',
    messagingSenderId: '932823267060',
    projectId: 'uni-craft-2c6b8',
    authDomain: 'uni-craft-2c6b8.firebaseapp.com',
    storageBucket: 'uni-craft-2c6b8.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAOTn1hp7mgNLyiVfTyfLNm_ZLCV7izh6o',
    appId: '1:932823267060:android:b89b70a8b6d60c149c10a1',
    messagingSenderId: '932823267060',
    projectId: 'uni-craft-2c6b8',
    storageBucket: 'uni-craft-2c6b8.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCA-GRIbCoW3Cefqxizb20AvF2UsRYeqKk',
    appId: '1:932823267060:ios:b8e191f4847671609c10a1',
    messagingSenderId: '932823267060',
    projectId: 'uni-craft-2c6b8',
    storageBucket: 'uni-craft-2c6b8.appspot.com',
    iosBundleId: 'com.example.uniCraft',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCA-GRIbCoW3Cefqxizb20AvF2UsRYeqKk',
    appId: '1:932823267060:ios:e954d23b0c062f9c9c10a1',
    messagingSenderId: '932823267060',
    projectId: 'uni-craft-2c6b8',
    storageBucket: 'uni-craft-2c6b8.appspot.com',
    iosBundleId: 'com.example.uniCraft.RunnerTests',
  );
}
